"""Command line interface for the delta-neutral volume bot."""
from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

from colorama import just_fix_windows_console

from .bot import DeltaNeutralVolumeBot
from .config import load_config

RESET = "\033[0m"
DIM = "\033[2m"
BOLD = "\033[1m"
LEVEL_COLORS = {
    logging.DEBUG: "\033[36m",
    logging.INFO: "\033[32m",
    logging.WARNING: "\033[33m",
    logging.ERROR: "\033[31m",
    logging.CRITICAL: "\033[41m",
}


class ColorFormatter(logging.Formatter):
    """Pretty log formatter with ANSI colors for console output."""

    def __init__(self) -> None:
        super().__init__(fmt="%(message)s", datefmt="%H:%M:%S")

    def format(self, record: logging.LogRecord) -> str:  # pragma: no cover - formatting logic
        message = record.getMessage()
        if record.exc_info:
            message = f"{message}\n{self.formatException(record.exc_info)}"
        timestamp = self.formatTime(record, self.datefmt)
        level_color = LEVEL_COLORS.get(record.levelno, "")
        level = f"{level_color}{BOLD}{record.levelname:<5}{RESET}"
        name = f"{DIM}{record.name}{RESET}"
        return f"{DIM}{timestamp}{RESET} {level} {name} {message}"


def _configure_logging(verbosity: int) -> None:
    just_fix_windows_console()
    level = logging.WARNING
    if verbosity == 1:
        level = logging.INFO
    elif verbosity >= 2:
        level = logging.DEBUG
    handler = logging.StreamHandler()
    handler.setLevel(level)
    handler.setFormatter(ColorFormatter())
    root_logger = logging.getLogger()
    root_logger.handlers.clear()
    root_logger.setLevel(level)
    root_logger.addHandler(handler)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Delta-neutral volume bot for AsterDEX futures")
    subparsers = parser.add_subparsers(dest="command")

    run_parser = subparsers.add_parser("run", help="Run the trading bot")
    run_parser.add_argument("--config", required=True, type=Path, help="Path to YAML/JSON configuration file")
    run_parser.add_argument("--verbosity", "-v", action="count", default=0, help="Increase logging verbosity")

    status_parser = subparsers.add_parser("status", help="Print the latest bot status from the status file")
    status_parser.add_argument(
        "--status-file",
        type=Path,
        default=Path("bot_status.json"),
        help="Status file generated by the bot",
    )
    status_parser.add_argument("--verbosity", "-v", action="count", default=0)

    return parser.parse_args()


def _print_status(path: Path) -> None:
    if not path.exists():
        raise SystemExit(f"Status file '{path}' does not exist. Run the bot with --status-file to generate one.")
    data = json.loads(path.read_text(encoding="utf-8"))
    lines = ["Bot status:"]
    for key, value in data.items():
        lines.append(f"  {key}: {value}")
    print("\n".join(lines))


def run_cli() -> None:
    args = _parse_args()
    _configure_logging(args.verbosity)

    if args.command == "status":
        _print_status(args.status_file)
        return

    if args.command != "run":
        raise SystemExit("A subcommand is required. Use --help for details.")

    long_account, short_account, bot_config = load_config(args.config)
    if bot_config.status_file is None:
        bot_config.status_file = Path("bot_status.json")
    bot = DeltaNeutralVolumeBot(long_account, short_account, bot_config)
    bot.run()


__all__ = ["run_cli"]