"""Command line interface for the delta-neutral volume bot."""
from __future__ import annotations

import argparse
import json
import logging
from decimal import Decimal
from pathlib import Path

from .bot import DeltaNeutralVolumeBot
from .config import BotConfig, load_config

LOG_FORMAT = "%(asctime)s %(levelname)s %(name)s: %(message)s"


def _configure_logging(verbosity: int) -> None:
    level = logging.WARNING
    if verbosity == 1:
        level = logging.INFO
    elif verbosity >= 2:
        level = logging.DEBUG
    logging.basicConfig(level=level, format=LOG_FORMAT)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Delta-neutral volume bot for AsterDEX futures")
    subparsers = parser.add_subparsers(dest="command")

    run_parser = subparsers.add_parser("run", help="Run the trading bot")
    run_parser.add_argument("--config", required=True, type=Path, help="Path to YAML/JSON configuration file")
    run_parser.add_argument("--dry-run", action="store_true", help="Run without hitting the live API")
    run_parser.add_argument("--cycles", type=int, default=None, help="Number of cycles to execute before stopping")
    run_parser.add_argument(
        "--target-volume",
        type=Decimal,
        default=None,
        help="Override the configured target volume (quote asset)",
    )
    run_parser.add_argument("--verbosity", "-v", action="count", default=0, help="Increase logging verbosity")

    status_parser = subparsers.add_parser("status", help="Print the latest bot status from the status file")
    status_parser.add_argument(
        "--status-file",
        type=Path,
        default=Path("bot_status.json"),
        help="Status file generated by the bot",
    )
    status_parser.add_argument("--verbosity", "-v", action="count", default=0)

    return parser.parse_args()


def _print_status(path: Path) -> None:
    if not path.exists():
        raise SystemExit(f"Status file '{path}' does not exist. Run the bot with --status-file to generate one.")
    data = json.loads(path.read_text(encoding="utf-8"))
    lines = ["Bot status:"]
    for key, value in data.items():
        lines.append(f"  {key}: {value}")
    print("\n".join(lines))


def _merge_overrides(bot_config: BotConfig, args: argparse.Namespace) -> BotConfig:
    if args.dry_run:
        bot_config.dry_run = True
    if args.target_volume is not None:
        bot_config.target_volume = Decimal(str(args.target_volume))
    return bot_config


def run_cli() -> None:
    args = _parse_args()
    _configure_logging(args.verbosity)

    if args.command == "status":
        _print_status(args.status_file)
        return

    if args.command != "run":
        raise SystemExit("A subcommand is required. Use --help for details.")

    long_account, short_account, bot_config = load_config(args.config)
    bot_config = _merge_overrides(bot_config, args)
    if bot_config.status_file is None:
        bot_config.status_file = Path("bot_status.json")
    bot = DeltaNeutralVolumeBot(long_account, short_account, bot_config)
    bot.run(max_cycles=args.cycles)


__all__ = ["run_cli"]
